"""create days, time_slots, weeks, tasks tables

Revision ID: 36b53d7968bc
Revises: 
Create Date: 2026-08-14 16:00:38.396618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b53d7968bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeks',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('week_id', sa.String(length=4), nullable=False),
    sa.Column('day_id', sa.String(length=3), nullable=False),
    sa.Column('time_id', sa.String(length=2), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('ticket', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('request', sa.String(length=1000), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('access_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'day_id', 'time_id', name='uq_tasks_week_day_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('weeks')
    op.drop_table('time_slots')
    op.drop_table('days')
    # ### end Alembic commands ###
